---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook
  namespace: cert-manager

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.6
    heritage: Tiller
    release: cert-manager
  name: cert-manager
  namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.6
    heritage: Tiller
    release: cert-manager
  name: cert-manager
  namespace: cert-manager
rules:
- apiGroups:
  - certmanager.k8s.io
  resources:
  - certificates
  - certificates/finalizers
  - issuers
  - clusterissuers
  - orders
  - orders/finalizers
  - challenges
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - events
  - services
  - pods
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.6
    heritage: Tiller
    release: cert-manager
  name: cert-manager
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.6
    heritage: Tiller
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    release: cert-manager
  name: cert-manager-view
  namespace: cert-manager
rules:
- apiGroups:
  - certmanager.k8s.io
  resources:
  - certificates
  - issuers
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.6
    heritage: Tiller
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    release: cert-manager
  name: cert-manager-edit
  namespace: cert-manager
rules:
- apiGroups:
  - certmanager.k8s.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook:auth-delegator
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager-webhook
  namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook:webhook-authentication-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager-webhook
  namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook:webhook-requester
  namespace: cert-manager
rules:
- apiGroups:
  - admission.certmanager.k8s.io
  resources:
  - certificates
  - issuers
  - clusterissuers
  verbs:
  - create

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook
  namespace: cert-manager
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    app: webhook
    release: cert-manager
  type: ClusterIP

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook
  namespace: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
      release: cert-manager
  template:
    metadata:
      annotations: null
      labels:
        app: webhook
        release: cert-manager
    spec:
      containers:
      - args:
        - --v=12
        - --secure-port=6443
        - --tls-cert-file=/certs/tls.crt
        - --tls-private-key-file=/certs/tls.key
        - --disable-admission-plugins=NamespaceLifecycle,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,Initializers
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/jetstack/cert-manager-webhook:v0.6.2
        imagePullPolicy: IfNotPresent
        name: webhook
        resources: {}
        volumeMounts:
        - mountPath: /certs
          name: certs
      serviceAccountName: cert-manager-webhook
      volumes:
      - name: certs
        secret:
          secretName: cert-manager-webhook-webhook-tls

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.6
    heritage: Tiller
    release: cert-manager
  name: cert-manager
  namespace: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
      release: cert-manager
  template:
    metadata:
      annotations: null
      labels:
        app: cert-manager
        release: cert-manager
    spec:
      containers:
      - args:
        - --cluster-resource-namespace=kube-system
        - --leader-election-namespace=$(POD_NAMESPACE)
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/jetstack/cert-manager-controller:v0.6.2
        imagePullPolicy: IfNotPresent
        name: cert-manager
        resources: {}
      serviceAccountName: cert-manager

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-ca-sync
  namespace: cert-manager
spec:
  jobTemplate:
    spec:
      backoffLimit: 20
      template:
        metadata:
          labels:
            app: ca-helper
        spec:
          containers:
          - args:
            - -config=/config/config
            image: quay.io/munnerz/apiextensions-ca-helper:v0.1.0
            imagePullPolicy: IfNotPresent
            name: ca-helper
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 32Mi
            volumeMounts:
            - mountPath: /config
              name: config
          restartPolicy: OnFailure
          serviceAccountName: cert-manager-webhook-ca-sync
          volumes:
          - configMap:
              name: cert-manager-webhook-ca-sync
            name: config
  schedule: '@weekly'

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-ca-sync
  namespace: cert-manager
spec:
  backoffLimit: 20
  template:
    metadata:
      labels:
        app: ca-helper
    spec:
      containers:
      - args:
        - -config=/config/config
        image: quay.io/munnerz/apiextensions-ca-helper:v0.1.0
        imagePullPolicy: IfNotPresent
        name: ca-helper
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
        volumeMounts:
        - mountPath: /config
          name: config
      restartPolicy: OnFailure
      serviceAccountName: cert-manager-webhook-ca-sync
      volumes:
      - configMap:
          name: cert-manager-webhook-ca-sync
        name: config

---
apiVersion: v1
data:
  config: |-
    {
        "apiServices": [
            {
                "name": "v1beta1.admission.certmanager.k8s.io",
                "secret": {
                    "name": "cert-manager-webhook-ca",
                    "namespace": "cert-manager",
                    "key": "tls.crt"
                }
            }
        ],
        "validatingWebhookConfigurations": [
            {
                "name": "cert-manager-webhook",
                "file": {
                    "path": "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
                }
            }
        ]
    }
kind: ConfigMap
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-ca-sync
  namespace: cert-manager

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-ca-sync
  namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-ca-sync
  namespace: cert-manager
rules:
- apiGroups:
  - ""
  resourceNames:
  - cert-manager-webhook-ca
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - cert-manager-webhook
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - get
  - update
- apiGroups:
  - apiregistration.k8s.io
  resourceNames:
  - v1beta1.admission.certmanager.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - update

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-ca-sync
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-ca-sync
subjects:
- kind: ServiceAccount
  name: cert-manager-webhook-ca-sync
  namespace: cert-manager

---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: v1beta1.admission.certmanager.k8s.io
  namespace: cert-manager
spec:
  group: admission.certmanager.k8s.io
  groupPriorityMinimum: 1000
  service:
    name: cert-manager-webhook
    namespace: cert-manager
  version: v1beta1
  versionPriority: 15

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-selfsign
  namespace: cert-manager
spec:
  selfSigned: {}

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-ca
  namespace: cert-manager
spec:
  commonName: ca.webhook.cert-manager
  duration: 43800h
  isCA: true
  issuerRef:
    name: cert-manager-webhook-selfsign
  secretName: cert-manager-webhook-ca

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-ca
  namespace: cert-manager
spec:
  ca:
    secretName: cert-manager-webhook-ca

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-webhook-tls
  namespace: cert-manager
spec:
  dnsNames:
  - cert-manager-webhook
  - cert-manager-webhook.cert-manager
  - cert-manager-webhook.cert-manager.svc
  duration: 8760h
  issuerRef:
    name: cert-manager-webhook-ca
  secretName: cert-manager-webhook-webhook-tls

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook
  namespace: cert-manager
webhooks:
- clientConfig:
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.certmanager.k8s.io/v1beta1/certificates
  failurePolicy: Fail
  name: certificates.admission.certmanager.k8s.io
  namespaceSelector:
    matchExpressions:
    - key: certmanager.k8s.io/disable-validation
      operator: NotIn
      values:
      - "true"
    - key: name
      operator: NotIn
      values:
      - cert-manager
  rules:
  - apiGroups:
    - certmanager.k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - certificates
- clientConfig:
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.certmanager.k8s.io/v1beta1/issuers
  failurePolicy: Fail
  name: issuers.admission.certmanager.k8s.io
  namespaceSelector:
    matchExpressions:
    - key: certmanager.k8s.io/disable-validation
      operator: NotIn
      values:
      - "true"
    - key: name
      operator: NotIn
      values:
      - cert-manager
  rules:
  - apiGroups:
    - certmanager.k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - issuers
- clientConfig:
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.certmanager.k8s.io/v1beta1/clusterissuers
  failurePolicy: Fail
  name: clusterissuers.admission.certmanager.k8s.io
  namespaceSelector:
    matchExpressions:
    - key: certmanager.k8s.io/disable-validation
      operator: NotIn
      values:
      - "true"
    - key: name
      operator: NotIn
      values:
      - cert-manager
  rules:
  - apiGroups:
    - certmanager.k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterissuers

